In [1]:
import pandas as pd

In [2]:
import MetaTrader5 as Mt5
import time
from skopt import gp_minimize
from skopt.space import Real
from skopt.space import Categorical

In [3]:
from functions import moving_resistance,moving_support,support,resistance

In [4]:
from data_functions import *

In [5]:

nowd=get_data('GOLD')
nowd['mtime']=pd.to_datetime(nowd['time'],unit='s')
nowd = nowd[nowd['mtime'].dt.date != pd.to_datetime('2015-01-02').date()]
nowd.reset_index(drop=True, inplace=True)
using_data=nowd

In [6]:
def yeardata(using_data,year):
    using_data2 = using_data[using_data['mtime'].dt.year == year]
    finalusing=using_data2.reset_index()
    jandata = finalusing[(finalusing['mtime'] >= f'{year}-01-01') & (finalusing['mtime'] < f'{year}-12-31')]
    jandata.reset_index(drop=True, inplace=True)

    jandata = jandata.drop('index', axis=1)
    return jandata

In [20]:
jandata=yeardata(using_data,2023)
jandata=nowd

In [8]:
from indicator import calculate_smma,calculate_rsi

In [21]:
jandata['smma_200']=calculate_smma(jandata['Close'],200)
jandata['smma_21']=calculate_smma(jandata['Close'],21)
jandata['smma_50']=calculate_smma(jandata['Close'],50)

jandata

,time,Open,High,Low,Close,tick_volume,spread,real_volume,mtime,smma_200,smma_21,smma_50
0,1420419600,1187.24,1188.40,1186.56,1187.75,195,55,0,2015-01-05 01:00:00,1192.416700,1184.308571,1188.579400
1,1420419900,1187.67,1188.25,1187.62,1188.05,115,57,0,2015-01-05 01:05:00,1192.416700,1184.308571,1188.579400
2,1420420200,1188.05,1188.15,1178.24,1180.14,214,45,0,2015-01-05 01:10:00,1192.416700,1184.308571,1188.579400
3,1420420500,1180.24,1181.82,1178.39,1181.62,275,58,0,2015-01-05 01:15:00,1192.416700,1184.308571,1188.579400
4,1420420800,1181.52,1181.62,1178.92,1180.42,187,53,0,2015-01-05 01:20:00,1192.416700,1184.308571,1188.579400
...,...,...,...,...,...,...,...,...,...,...,...,...
664934,1716575700,2335.13,2335.13,2332.23,2333.72,1016,31,0,2024-05-24 18:35:00,2347.262956,2338.402399,2338.478937
664935,1716576000,2333.83,2334.98,2333.32,2334.37,575,31,0,2024-05-24 18:40:00,2347.198492,2338.210380,2338.396758
664936,1716576300,2334.43,2334.46,2332.33,2334.15,634,31,0,2024-05-24 18:45:00,2347.133249,2338.017029,2338.311823
664937,1716576600,2334.12,2334.81,2333.05,2333.35,520,31,0,2024-05-24 18:50:00,2347.064333,2337.794790,2338.212587
664938,1716576900,2333.39,2334.81,2332.89,2334.45,476,31,0,2024-05-24 18:55:00,2347.001261,2337.635514,2338.137335

In [22]:
jandata['rsi']=calculate_rsi(jandata['Close'])
jandata

,time,Open,High,Low,Close,tick_volume,spread,real_volume,mtime,smma_200,smma_21,smma_50,rsi
0,1420419600,1187.24,1188.40,1186.56,1187.75,195,55,0,2015-01-05 01:00:00,1192.416700,1184.308571,1188.579400,NaN
1,1420419900,1187.67,1188.25,1187.62,1188.05,115,57,0,2015-01-05 01:05:00,1192.416700,1184.308571,1188.579400,100.000000
2,1420420200,1188.05,1188.15,1178.24,1180.14,214,45,0,2015-01-05 01:10:00,1192.416700,1184.308571,1188.579400,3.654080
3,1420420500,1180.24,1181.82,1178.39,1181.62,275,58,0,2015-01-05 01:15:00,1192.416700,1184.308571,1188.579400,18.369453
4,1420420800,1181.52,1181.62,1178.92,1180.42,187,53,0,2015-01-05 01:20:00,1192.416700,1184.308571,1188.579400,16.345271
...,...,...,...,...,...,...,...,...,...,...,...,...,...
664934,1716575700,2335.13,2335.13,2332.23,2333.72,1016,31,0,2024-05-24 18:35:00,2347.262956,2338.402399,2338.478937,40.013870
664935,1716576000,2333.83,2334.98,2333.32,2334.37,575,31,0,2024-05-24 18:40:00,2347.198492,2338.210380,2338.396758,34.170472
664936,1716576300,2334.43,2334.46,2332.33,2334.15,634,31,0,2024-05-24 18:45:00,2347.133249,2338.017029,2338.311823,39.420544
664937,1716576600,2334.12,2334.81,2333.05,2333.35,520,31,0,2024-05-24 18:50:00,2347.064333,2337.794790,2338.212587,30.190390
664938,1716576900,2333.39,2334.81,2332.89,2334.45,476,31,0,2024-05-24 18:55:00,2347.001261,2337.635514,2338.137335,36.916667

### Asumptions for the check distance function
##### Checks if the smma distance is overcrowded or not


* The 200 smma is always greater than the 50 smma and 21 smma (and vice versa)
* The 50 smma is alays greater than the 21 smma (and vice versa)

In [11]:
def check_dist(sma1,sma2,sma3,allowed_dist):
    diff_dist1=sma2-sma1
    diff_dist2=sma3-sma2
    return_value=True
    if diff_dist1<allowed_dist:
        return_value=False
    if diff_dist2<allowed_dist:
        return_value=False
        
    return return_value

In [12]:
def check_engulf(n_candle,p_candle):
    return_vale=True
    f_bodysize=abs(n_candle['Close']-n_candle['Open'])
    p_bodysize=abs(p_candle['Close']-p_candle['Open'])
    bd_diff=f_bodysize-p_bodysize
    
    
    if candletype(n_candle)==candletype(p_candle):
        return_vale=False

    else:
       
        if bd_diff<p_bodysize:
            return_vale=False

      
            
    return return_vale

In [13]:
def confirn_dist_smma(candle,allowed_d):
    return_value=True
    if candletype(candle)==1:
        distance=abs(candle['smma_21']-candle['High'])
        if distance>allowed_d:
            return_value=False
    else:
        distance=abs(candle['smma_21']-candle['Low'])
        if distance>allowed_d:
            return_value=False
    
    return return_value

In [14]:
def check_overunder(candle):
    return_value=True
    if candletype(candle)==1:
        if candle['Open']<candle['smma_21']:
            return_value=False
        if candle['Open']<candle['smma_50']:
            return_value=False
        if candle['Open']<candle['smma_200']:
            return_value=False
    else:
        if candle['Open']>candle['smma_21']:
            return_value=False
        if candle['Open']>candle['smma_50']:
            return_value=False
        if candle['Open']>candle['smma_200']:
            return_value=False
            
    return return_value

In [15]:
def disjunction(data,index,tradetype):
    if tradetype==1:
        res_point=resistance(data,index,2,1)
        rsi_point=data.loc[res_point]['rsi']
        if rsi_point<40:
            return True
        else:
            return False
    else:
        sup_point=support(data,index,2,1)
        rsi_point=data.loc[sup_point]['rsi']
        if rsi_point>60:
            return True
        else:
            return False

In [23]:
def greedy(data,ssma_dist,all_highlow,sma_sl_val,sl_adj,tp_adj,cash):
    trades=[]
    trade=0
    opendate=None
    price=0
    
    # tp=0
    # sl=0
    cash=cash
    iid=None
    
    
    for i in range(len(data)):
        val_h=data.loc[i]
        lower_price=val_h['Low']
        upper_price=val_h['High']
        norm_price=val_h['Close']
        smma_distvalue=check_dist(val_h['smma_21'],val_h['smma_50'],val_h['smma_200'],ssma_dist)
        if trade==0:
            if smma_distvalue == True:
                if check_overunder(val_h)==True:
                    if check_engulf(val_h,data.loc[i-1])==True:
                        if confirn_dist_smma(val_h,all_highlow)==True:
                            if val_h['rsi']>50:
                                if candletype(val_h)==1:
                                    trade=1
                                    price=val_h['Close']
                                    # sl=val_h[f'smma_{sma_sl_val}']-sl_adj
                                    # tp=price+(price-sl)+tp_adj
                                    opendate=val_h['time']
                                    # print(i)
                                    iid=generate_random_id()
                                else:
                                    trade=-1
                                    price=val_h['Close']
                                    # sl=val_h[f'smma_{sma_sl_val}']+sl_adj
                                    # tp=price-(sl-price)-tp_adj
                                    opendate=val_h['time']
                                    iid=generate_random_id()
                                    # print(i)
                                    # print(val_h['mtime'])
        elif trade==1:
            if disjunction(jandata,i,trade)==True:
                closedate=val_h['time'] 
                profit=calc_prof(val_h['Close'],price)
                cash=cash+profit
                trades.append(('Buy',opendate,closedate,profit,iid))
                trade=0
                continue
            
        elif trade==-1:
            if disjunction(jandata,i,trade)==True:
                closedate=val_h['time'] 
                profit=calc_prof(price,val_h['Close'])
                cash=cash+profit
                trades.append(('Sell',opendate,closedate,profit,iid))
                trade=0
                continue
                    
            
    return trades,cash#,distcounter,statuscounter,distcounter2,statuscounter2

In [24]:
l,k=greedy(jandata,0.1,0.5,200,0,0,10000)

In [25]:
k

9974.539999999999

In [75]:
def convert_timestamps(data):
    new_data = []
    for entry in data:
        readable_start = datetime.datetime.utcfromtimestamp(entry[1]).strftime('%Y-%m-%d %H:%M:%S')
        readable_end = datetime.datetime.utcfromtimestamp(entry[2]).strftime('%Y-%m-%d %H:%M:%S')
        new_entry = (entry[0], readable_start, readable_end, entry[3], entry[4])
        new_data.append(new_entry)
    return new_data

In [40]:
ll=convert_timestamps(l)
ll

[('Sell',
  '2023-02-24 18:45:00',
  '2023-02-28 17:00:00',
  -9.646327055999336,
  'M4E')]

In [26]:
l

[('Sell', 1423535400, 1423541400, -2.5399999999999636, 'miu'),
 ('Sell', 1423619700, 1423620300, -0.8800000000001091, 'hqb'),
 ('Sell', 1425501300, 1425522300, -0.7899999999999636, 'KGy'),
 ('Sell', 1425615300, 1425615900, -0.3200000000001637, 'uVw'),
 ('Sell', 1426627800, 1426628100, -0.4700000000000273, 'N9w'),
 ('Sell', 1427843400, 1427862000, -3.790000000000191, 'oRp'),
 ('Sell', 1428460500, 1428461100, 0.32999999999992724, 'P9U'),
 ('Sell', 1428564600, 1428573900, 1.7200000000000273, 'j4c'),
 ('Sell', 1429049700, 1429070700, -1.6800000000000637, '9dT'),
 ('Sell', 1429235700, 1429236000, -0.39000000000010004, 'xBO'),
 ('Sell', 1429908900, 1429909800, 0.07999999999992724, 'cga'),
 ('Sell', 1435273800, 1435281900, -0.7000000000000455, 'RuY'),
 ('Sell', 1436909700, 1436910600, -0.43000000000006366, '1tt'),
 ('Sell', 1437704100, 1437720300, 7.1099999999999, 'hYB'),
 ('Sell', 1439492700, 1439493300, -0.029999999999972715, 'X7D'),
 ('Sell', 1441254600, 1441255200, -0.38999999999987267, 'hB4'),
 ('Sell', 1441258800, 1441264200, -0.2699999999999818, 'Ji0'),
 ('Sell', 1441851300, 1441863900, 0.1899999999998272, 'w19'),
 ('Sell', 1443489900, 1443490500, 0.12000000000011823, 'JqV'),
 ('Sell', 1443751500, 1443752700, -0.2300000000000182, 'NjF'),
 ('Sell', 1443753300, 1443753600, 0.10999999999989996, 'sls'),
 ('Sell', 1445323800, 1445332200, -2.9300000000000637, '0xk'),
 ('Sell', 1446844200, 1447041300, -3.519999999999982, '5fl'),
 ('Sell', 1448490300, 1448490600, -0.12000000000011823, '4vN'),
 ('Sell', 1449543000, 1449575700, -3.0499999999999545, 'Rob'),
 ('Sell', 1450833300, 1450836900, -0.7100000000000364, 'uRp'),
 ('Sell', 1451313600, 1451339100, 3.7799999999999727, 'YxJ'),
 ('Sell', 1453406100, 1453411200, -7.099999999999909, 'W5i'),
 ('Sell', 1459386600, 1459389300, 0.4900000000000091, 'oGs'),
 ('Sell', 1462331400, 1462343400, 4.439999999999827, 'D5v'),
 ('Sell', 1463623200, 1463623500, 0.2799999999999727, '1oO'),
 ('Sell', 1464000900, 1464026400, 3.4199999999998454, 'YKO'),
 ('Sell', 1464335700, 1464339300, -3.0700000000001637, 'BMc'),
 ('Sell', 1464906600, 1464929400, 0.05999999999994543, 'gaK'),
 ('Sell', 1466134800, 1466147100, -2.2799999999999727, 'BI1'),
 ('Sell', 1469042700, 1469080500, 4.039999999999964, 'NRy'),
 ('Sell', 1471442700, 1471446300, -1.3500000000001364, 'Eyb'),
 ('Sell', 1471850100, 1471850400, -0.2699999999999818, 'CWA'),
 ('Sell', 1474336500, 1474347000, -2.380000000000109, 'b6B'),
 ('Sell', 1475048400, 1475051700, -0.4700000000000273, 'ptg'),
 ('Sell', 1475565000, 1475565300, -0.21000000000003638, '0Zc'),
 ('Sell', 1475668500, 1475668800, 0.01999999999998181, 'k21'),
 ('Sell', 1476669900, 1476670200, -0.44000000000005457, 'v6l'),
 ('Sell', 1477013700, 1477014600, -0.16999999999984539, 'uWN'),
 ('Sell', 1481099700, 1481107800, -3.8099999999999454, 'fpI'),
 ('Sell', 1482450300, 1482460800, -0.4800000000000182, 'FwI'),
 ('Sell', 1483745100, 1483745400, -0.11000000000012733, '6Or'),
 ('Sell', 1485301200, 1485347100, 5.5, 'lZX'),
 ('Sell', 1486704300, 1486725300, 0.0, 'QjB'),
 ('Sell', 1487166000, 1487169000, -1.4100000000000819, 'NA4'),
 ('Sell', 1487570400, 1487570700, -0.01999999999998181, '1y8'),
 ('Sell', 1488546600, 1488571500, 0.4500000000000455, 'T2m'),
 ('Sell', 1488835200, 1488836100, 0.20000000000004547, 'bot'),
 ('Sell', 1489120200, 1489120800, -0.18000000000006366, 'Akl'),
 ('Sell', 1489122900, 1489145100, 1.6800000000000637, 'dSm'),
 ('Sell', 1489460400, 1489464300, -1.490000000000009, 'iFv'),
 ('Sell', 1489540200, 1489540500, -0.6100000000001273, 'uYd'),
 ('Sell', 1490943900, 1490947200, -1.150000000000091, 'KyZ'),
 ('Sell', 1491402300, 1491415500, 4.789999999999964, 'yUN'),
 ('Sell', 1491425400, 1491432600, -8.450000000000045, 'Hkc'),
 ('Sell', 1491809100, 1491813000, -1.2799999999999727, 'yvr'),
 ('Sell', 1492608900, 1492626300, 2.9700000000000273, 'NfN'),
 ('Sell', 1492756200, 1492773900, -0.6399999999998727, '4ed'),
 ('Sell', 1493175300, 1493181300, -0.35999999999989996, '0xh'),
 ('Sell', 1493636700, 1493637600, -0.15000000000009095, 'l2V'),
 ('Sell', 1495611300, 1495621800, 1.4500000000000455, '9uo'),
 ('Sell', 1496395800, 1496398800, -0.6300000000001091, 'fYt'),
 ('Sell', 1497850200, 1497852600, -0.5199999999999818, 'NxL'),
 ('Sell', 1499069700, 1499082300, 1.5199999999999818, 'ewJ'),
 ('Sell', 1499119500, 1499119800, -0.12999999999988177, '1aw'),
 ('Sell', 1499194200, 1499216700, -0.6799999999998363, 'wnP'),
 ('Sell', 1499755200, 1499756100, -0.009999999999990905, 'xG3'),
 ('Sell', 1501025100, 1501042200, 2.3300000000001546, 'wxN'),
 ('Sell', 1501734300, 1501747500, 1.0699999999999363, 'Vq9'),
 ('Sell', 1502121300, 1502124900, -1.4299999999998363, 'TDF'),
 ('Sell', 1503617400, 1503643200, -0.6700000000000728, 'IlR'),
 ('Sell', 1504166400, 1504166700, 0.4099999999998545, 'y9k'),
 ('Sell', 1504739400, 1504740000, -0.14000000000010004, 'fiU'),
 ('Sell', 1504740900, 1504741200, -0.03999999999996362, 'ohL'),
 ('Sell', 1505359800, 1505368800, 0.6599999999998545, '0P5'),
 ('Sell', 1507254300, 1507254600, -0.009999999999990905, 'brq'),
 ('Sell', 1509712500, 1509720600, -1.4700000000000273, '3XL'),
 ('Sell', 1510353600, 1510354200, -0.2400000000000091, 'WBe'),
 ('Sell', 1510872900, 1510873200, 0.05999999999994543, 'n9I'),
 ('Sell', 1512696300, 1512702000, -1.0, 'tdK'),
 ('Sell', 1515411600, 1515414000, -0.6200000000001182, 'lCB'),
 ('Sell', 1517809200, 1517817300, -1.6299999999998818, 'pPm'),
 ('Sell', 1519128600, 1519146900, -2.0900000000001455, 'sOZ'),
 ('Sell', 1519742100, 1519765800, 14.910000000000082, 'Nua'),
 ('Sell', 1520944200, 1520944500, -0.19000000000005457, 'Z5T'),
 ('Sell', 1521145500, 1521145800, 0.5299999999999727, 'udg'),
 ('Sell', 1521434100, 1521434400, -0.19000000000005457, 'nPG'),
 ('Sell', 1524265800, 1524461400, 1.8100000000001728, 'DOe'),
 ('Sell', 1524786000, 1524815700, -0.599999999999909, 'cpj'),
 ('Sell', 1525311300, 1525311900, 0.01999999999998181, '8qE'),
 ('Sell', 1526347800, 1526348100, -0.01999999999998181, 'ht6'),
 ('Sell', 1526348700, 1526349000, 0.17000000000007276, 'vT4'),
 ('Sell', 1526423100, 1526436000, -1.0499999999999545, 'b4h'),
 ('Sell', 1526625000, 1526634300, -1.3299999999999272, 'akj'),
 ('Sell', 1528161300, 1528175700, -0.2999999999999545, 'HeW'),
 ('Sell', 1528443300, 1528456800, -2.2199999999998, 'iQr'),
 ('Sell', 1529306700, 1529307000, -0.14000000000010004, 'OTM'),
 ('Sell', 1530151500, 1530157800, -1.009999999999991, 'Y87'),
 ('Sell', 1530575100, 1530582600, -0.6800000000000637, 'XXy'),
 ('Sell', 1531984200, 1532019000, 8.329999999999927, '8xC'),
 ('Sell', 1532655600, 1532672100, -0.6399999999998727, 'hIq'),
 ('Sell', 1533019800, 1533024600, -1.4099999999998545, 'c28'),
 ('Sell', 1533173100, 1533175200, -0.38000000000010914, 'f8r'),
 ('Sell', 1533681000, 1533681600, -0.009999999999990905, 'Iyn'),
 ('Sell', 1534198800, 1534199100, 0.009999999999990905, 'RIV'),
 ('Sell', 1534298400, 1534327500, 5.259999999999991, 'tea'),
 ('Sell', 1538986200, 1538986500, 0.08999999999991815, 'btw'),
 ('Sell', 1538992800, 1539002700, 2.349999999999909, '0An'),
 ('Sell', 1541019000, 1541023800, -2.230000000000018, 'tTn'),
 ('Sell', 1541567700, 1541571600, -2.990000000000009, 'Mxd'),
 ('Sell', 1547026200, 1547049300, -2.240000000000009, 'bnZ'),
 ('Sell', 1548138000, 1548144600, -0.6000000000001364, '7qw'),
 ('Sell', 1549503600, 1549526100, 3.2899999999999636, 'AEB'),
 ('Sell', 1551791700, 1551792900, -0.5299999999999727, 'jK6'),
 ('Sell', 1554168000, 1554171300, 0.21000000000003638, 'AWd'),
 ('Sell', 1554204000, 1554209700, -1.6299999999998818, 'llb'),
 ('Sell', 1554453600, 1554454200, -0.05999999999994543, '51Z'),
 ('Sell', 1555022700, 1555023300, 0.21000000000003638, 'ynX'),
 ('Sell', 1555292700, 1555314000, 1.75, 'gjD'),
 ('Sell', 1555424700, 1555449900, 7.990000000000009, 'aRY'),
 ('Sell', 1555545000, 1555553100, -0.6300000000001091, '5Cr'),
 ('Sell', 1555571400, 1555586100, -2.480000000000018, 'S9D'),
 ('Sell', 1556020500, 1556046900, 1.3800000000001091, 'jYl'),
 ('Sell', 1556781000, 1556781300, 0.0, 'O3P'),
 ('Sell', 1557746100, 1557746400, 0.5, 'wqp'),
 ('Sell', 1558336200, 1558363800, 0.4700000000000273, 'NKz'),
 ('Sell', 1559077200, 1559085600, -1.5, 'yBM'),
 ('Sell', 1559222400, 1559227200, -1.3300000000001546, 'd25'),
 ('Sell', 1564605600, 1564606200, -0.08999999999991815, '0hw'),
 ('Sell', 1566201600, 1566223200, 8.549999999999955, 'Jgy'),
 ('Sell', 1569831300, 1569831600, -0.30999999999994543, '1k5'),
 ('Sell', 1570756200, 1570763100, -0.4600000000000364, 'uX1'),
 ('Sell', 1571180400, 1571196900, -3.3599999999999, 'Qt9'),
 ('Sell', 1572400200, 1572404100, -1.5399999999999636, 'RHn'),
 ('Sell', 1574378700, 1574379000, 0.009999999999990905, 'ZnM'),
 ('Sell', 1574649000, 1574649300, 0.11999999999989086, 'wa1'),
 ('Sell', 1580455500, 1580460600, -1.3200000000001637, 'Jz4'),
 ('Sell', 1581404100, 1581420900, -0.5099999999999909, 'cTe'),
 ('Sell', 1593675300, 1593696600, -4.660000000000082, 'tC3'),
 ('Sell', 1597043400, 1597052100, -3.8400000000001455, 'xjM'),
 ('Sell', 1611726000, 1611726300, 0.540000000000191, '9c6'),
 ('Sell', 1612505100, 1612511700, -2.6599999999998545, 'H9Y'),
 ('Sell', 1628214000, 1628262300, 4.9500000000000455, 'eG3'),
 ('Sell', 1629882300, 1629882600, -0.8700000000001182, '6gx'),
 ('Sell', 1633657800, 1633669200, -3.0800000000001546, '6jR'),
 ('Sell', 1640119800, 1640126100, -0.43000000000006366, '8hf'),
 ('Sell', 1644556500, 1644575100, -1.0299999999999727, 'i79'),
 ('Sell', 1645619100, 1645619700, -1.650000000000091, 'olg'),
 ('Sell', 1647951600, 1647952200, -0.7899999999999636, 'ofK'),
 ('Sell', 1655259000, 1655261100, -1.6900000000000546, 'lnl'),
 ('Sell', 1657236300, 1657249800, -1.5, 'Q0t'),
 ('Sell', 1663716300, 1663726800, -0.8099999999999454, 'ZGa'),
 ('Sell', 1677264300, 1677277200, -0.44000000000005457, 'tcE'),
 ('Sell', 1686189900, 1686190200, 0.0500000000001819, 'GkT'),
 ('Sell', 1687823400, 1687827900, -0.6700000000000728, 'Xqy'),
 ('Sell', 1690162800, 1690177200, 0.6699999999998454, 'GXJ'),
 ('Sell', 1690250100, 1690262100, -7.370000000000118, 'sYU'),
 ('Sell', 1691437500, 1691438100, -0.09999999999990905, 'jqM'),
 ('Sell', 1692236100, 1692237900, 0.2799999999999727, 'EWM'),
 ('Sell', 1694216700, 1694405400, -1.4500000000000455, 'psk'),
 ('Sell', 1695621600, 1695638100, -0.4500000000000455, 'wFj'),
 ('Sell', 1698876600, 1698876900, 0.4099999999998545, 'vo4'),
 ('Sell', 1709099400, 1709105700, 0.2999999999999545, 'wS4')]

In [77]:
ty=l

In [26]:
import datetime
import plotly.graph_objects as go
import plotly.offline as pyo
import plotly.io as pio

In [78]:
fig = go.Figure(data=[go.Candlestick(x=jandata.mtime,
                open=jandata['Open'],
                high=jandata['High'],
                low=jandata['Low'],
                close=jandata['Close'])])

# Customize the layout
fig.add_trace(go.Scatter(x=jandata['mtime'], y=jandata['smma_21'], mode='lines', name='SMMA 21', line=dict(color='blue', width=1.5)))
fig.add_trace(go.Scatter(x=jandata['mtime'], y=jandata['smma_50'], mode='lines', name='SMMA 50', line=dict(color='orange', width=1.5)))
fig.add_trace(go.Scatter(x=jandata['mtime'], y=jandata['smma_200'], mode='lines', name='SMMA 100', line=dict(color='purple', width=1.5)))
trades_datetime = [(trade[0], pd.to_datetime(trade[1], unit='s'), pd.to_datetime(trade[2], unit='s'), trade[3],trade[4]) for trade in ty]
unique_dates = jandata['mtime'].dt.date.unique()


# Plot trades on the chart
for trade in trades_datetime:
    trade_type, entry_time, exit_time, profit,idd = trade
    if trade_type == 'Buy':
        color = 'green'
    elif trade_type == 'Sell':
        color = 'red'

    fig.add_trace(go.Scatter(x=[entry_time, exit_time], y=[jandata.loc[jandata['mtime'] == entry_time, 'Low'].values[0], jandata.loc[jandata['mtime'] == exit_time, 'High'].values[0]],
                             mode='markers+lines',
                             name=f'{trade_type} Trade',
                             marker=dict(color=color, size=8),
                             line=dict(color=color, width=2),
                             text=f'Profit: {profit:.2f} ,id : {idd}'))
                            

# Customize the layout
fig.update_layout(title='Forex Candlestick Chart with Trades',
                  xaxis_title='Date',
                  yaxis_title='Price',
                  xaxis_rangeslider_visible=True,
                  xaxis=dict(tickvals=[pd.to_datetime(date) for date in unique_dates],
                             ticktext=[date.strftime('%Y-%m-%d') for date in unique_dates]))

# Add horizontal lines for each day
for date in unique_dates:
    fig.add_shape(type='line',
                  x0=pd.to_datetime(date),
                  x1=pd.to_datetime(date) + pd.Timedelta(days=1),
                  y0=jandata['Low'].min(),
                  y1=jandata['High'].max(),
                  line=dict(color='black', width=1, dash='dash'))

# Show the plot
pio.write_html(fig, 'gr.html')
# fig.show()

In [71]:
from plotly.subplots import make_subplots

In [79]:


# Create subplots: 2 rows, 1 column
fig = make_subplots(rows=2, cols=1, shared_xaxes=True, 
                    vertical_spacing=0.2, subplot_titles=('Candlestick Chart', 'RSI'),
                    row_heights=[0.7, 0.3])

# Add candlestick chart
fig.add_trace(go.Candlestick(x=jandata['mtime'],
                             open=jandata['Open'],
                             high=jandata['High'],
                             low=jandata['Low'],
                             close=jandata['Close']),
              row=1, col=1)

# Add SMMA lines
fig.add_trace(go.Scatter(x=jandata['mtime'], y=jandata['smma_21'], mode='lines', name='SMMA 21', line=dict(color='blue', width=1.5)),
              row=1, col=1)
fig.add_trace(go.Scatter(x=jandata['mtime'], y=jandata['smma_50'], mode='lines', name='SMMA 50', line=dict(color='orange', width=1.5)),
              row=1, col=1)
fig.add_trace(go.Scatter(x=jandata['mtime'], y=jandata['smma_200'], mode='lines', name='SMMA 200', line=dict(color='purple', width=1.5)),
              row=1, col=1)

# Convert trades to datetime and plot them on the chart
trades_datetime = [(trade[0], pd.to_datetime(trade[1], unit='s'), pd.to_datetime(trade[2], unit='s'), trade[3], trade[4]) for trade in ty]
unique_dates = jandata['mtime'].dt.date.unique()

# Plot trades on the chart
for trade in trades_datetime:
    trade_type, entry_time, exit_time, profit, idd = trade
    if trade_type == 'Buy':
        color = 'green'
    elif trade_type == 'Sell':
        color = 'red'

    fig.add_trace(go.Scatter(x=[entry_time, exit_time],
                             y=[jandata.loc[jandata['mtime'] == entry_time, 'Low'].values[0], jandata.loc[jandata['mtime'] == exit_time, 'High'].values[0]],
                             mode='markers+lines',
                             name=f'{trade_type} Trade',
                             marker=dict(color=color, size=8),
                             line=dict(color=color, width=2),
                             text=f'Profit: {profit:.2f}, id: {idd}'),
                  row=1, col=1)

# Add RSI trace
fig.add_trace(go.Scatter(x=jandata['mtime'], y=jandata['rsi'], mode='lines', name='RSI', line=dict(color='black', width=1.5)),
              row=2, col=1)

# Customize the layout
fig.update_layout(title='Forex Candlestick Chart with Trades, SMMA, and RSI',
                  xaxis1_title='Date',
                  yaxis1_title='Price',
                  xaxis2_title='Date',
                  yaxis2_title='RSI',
                  xaxis1_rangeslider_visible=False,
                  xaxis2_rangeslider_visible=True,
                  xaxis1=dict(tickvals=[pd.to_datetime(date) for date in unique_dates],
                              ticktext=[date.strftime('%Y-%m-%d') for date in unique_dates]))

# Add horizontal lines for each day in the candlestick chart
for date in unique_dates:
    fig.add_shape(type='line',
                  x0=pd.to_datetime(date),
                  x1=pd.to_datetime(date) + pd.Timedelta(days=1),
                  y0=jandata['Low'].min(),
                  y1=jandata['High'].max(),
                  line=dict(color='black', width=1, dash='dash'),
                  row=1, col=1)

# Show the plot
pio.write_html(fig, 'gr1.html')
# fig.show()

In [64]:
o=support(jandata,765,2,1)
o

763
i ma mright 1812.7
central 1812.85 time 2023-02-24 18:35:00
i ma mleft 1812.85
left,right False False
762
i ma mright 1812.7
central 1813.74 time 2023-02-24 18:30:00
i ma mleft 1813.02
left,right False False
761
i ma mright 1812.85
central 1813.02 time 2023-02-24 18:25:00
i ma mleft 1812.04
left,right False False
760
i ma mright 1812.85
central 1812.04 time 2023-02-24 18:20:00
i ma mleft 1810.81
left,right False False
759
i ma mright 1813.02
central 1810.81 time 2023-02-24 18:15:00
i ma mleft 1809.6
left,right False False
758
i ma mright 1812.04
central 1809.6 time 2023-02-24 18:10:00
i ma mleft 1809.6
left,right False False
757
i ma mright 1810.81
central 1811.3 time 2023-02-24 18:05:00
i ma mleft 1810.29
left,right False False

758

In [66]:
l=jandata.loc[758]['mtime']
l

Timestamp('2023-02-24 18:10:00')